import AuthWrapper from "@/app/components/auth/AuthWrapper";
import { Geist, Geist_Mono } from "next/font/google";
import { Footer } from "./components/home/Footer";
import Header from "./components/home/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`flex flex-col min-h-screen`}>
        <Header />
        <AuthWrapper className="flex-grow">{children}</AuthWrapper>
        <Footer />
      </body>
    </html>
  );
}
